{{- if .Values.defaultPolicy -}}
---
apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
  name: default-policy
  annotations:
    description: traces default events
spec:
  scope:
    - container=new
  rules:
    - event: syscalls
{{- end }}
